services:
  frontend:
    image: ghcr.io/sophiekeesing/lernfeld-8/frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: ghcr.io/sophiekeesing/lernfeld-8/backend:latest
    ports:
      - "5000:5000"
    restart: always
